<?php
/**
 * Generated CSS cache for IGP Pro brand tokens.
 *
 * @package IGP_Pro
 */

defined( 'ABSPATH' ) || exit;

if ( ! defined( 'IGP_PRO_BRAND_CSS_CACHE_OPTION' ) ) {
	define( 'IGP_PRO_BRAND_CSS_CACHE_OPTION', 'igp_pro_brand_css_cache' );
}

/**
 * Ensure generated CSS storage exists.
 *
 * @return bool
 */
function igp_pro_ensure_generated_css_storage(): bool {
	$dir = igp_pro_path( 'storage/generated-css' );

	if ( ! is_dir( $dir ) && ! wp_mkdir_p( $dir ) ) {
		return false;
	}

	$htaccess = trailingslashit( $dir ) . '.htaccess';
	if ( ! file_exists( $htaccess ) ) {
		file_put_contents( $htaccess, "Options -Indexes\n" ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
	}

	$index = trailingslashit( $dir ) . 'index.php';
	if ( ! file_exists( $index ) ) {
		file_put_contents( $index, "<?php\n// Silence is golden.\n" ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
	}

	return true;
}

/**
 * Convert token map to deterministic hash.
 *
 * @param array<string,mixed> $tokens Tokens.
 * @return string
 */
function igp_pro_hash_design_tokens( array $tokens ): string {
	return substr( md5( wp_json_encode( $tokens ) ), 0, 12 );
}

/**
 * Build generated brand CSS.
 *
 * @param array<string,array<string,string>> $tokens Tokens.
 * @return string
 */
function igp_pro_build_brand_css( array $tokens ): string {
	$css = array();
	$c   = $tokens['colors'] ?? array();
	$t   = $tokens['typography'] ?? array();
	$s   = $tokens['spacing'] ?? array();
	$r   = $tokens['radius'] ?? array();
	$sh  = $tokens['shadow'] ?? array();
	$b   = $tokens['buttons'] ?? array();
	$co  = $tokens['containers'] ?? array();
	$su  = $tokens['surfaces'] ?? array();

	$scope = '.igp-brand-scope, .entry-content .igp-block, .wp-block-post-content .igp-block, .igp-block, .igp-page-title';
	$css[] = '/* Generated by IGP Pro Brand Engine. Do not edit directly. */';
	$css[] = $scope . ' {';
	$map   = array(
		'--igp-brand'                 => $c['brand'] ?? '#fd4621',
		'--igp-brand-dark'            => $c['brand_dark'] ?? '#d93412',
		'--igp-ink'                   => $c['ink'] ?? '#111827',
		'--igp-muted'                 => $c['muted'] ?? '#5b667a',
		'--igp-line'                  => $c['line'] ?? '#e8edf3',
		'--igp-soft'                  => $c['soft'] ?? '#f6f8fb',
		'--igp-sand'                  => $c['sand'] ?? '#fff6ef',
		'--igp-card'                  => $c['card'] ?? '#ffffff',
		'--igp-white'                 => $c['white'] ?? '#ffffff',
		'--igp-font-family'           => $t['font_family'] ?? 'inherit',
		'--igp-heading-weight'        => $t['heading_weight'] ?? '850',
		'--igp-body-weight'           => $t['body_weight'] ?? '500',
		'--igp-heading-letter-spacing'=> $t['heading_letter_spacing'] ?? '-0.055em',
		'--igp-hero-size'             => $t['hero_size'] ?? 'clamp(44px, 7vw, 92px)',
		'--igp-section-heading-size'  => $t['section_heading_size'] ?? 'clamp(30px, 4vw, 54px)',
		'--igp-body-size'             => $t['body_size'] ?? '16px',
		'--igp-section-y'             => $s['section_y'] ?? 'clamp(44px, 7vw, 88px)',
		'--igp-block-gap'             => $s['block_gap'] ?? '24px',
		'--igp-card-padding'          => $s['card_padding'] ?? '24px',
		'--igp-button-padding-y'      => $s['button_padding_y'] ?? '14px',
		'--igp-button-padding-x'      => $s['button_padding_x'] ?? '24px',
		'--igp-radius-sm'             => $r['sm'] ?? '12px',
		'--igp-radius'                => $r['md'] ?? '20px',
		'--igp-radius-lg'             => $r['lg'] ?? '32px',
		'--igp-radius-pill'           => $r['pill'] ?? '999px',
		'--igp-shadow'                => $sh['card'] ?? '0 18px 45px rgba(17, 24, 39, .10)',
		'--igp-shadow-soft'           => $sh['soft'] ?? '0 10px 28px rgba(17, 24, 39, .08)',
		'--igp-button-radius'         => $b['radius'] ?? '999px',
		'--igp-button-font-weight'    => $b['font_weight'] ?? '850',
		'--igp-container-narrow'      => $co['narrow'] ?? '820px',
		'--igp-container-default'     => $co['default'] ?? '1040px',
		'--igp-container-wide'        => $co['wide'] ?? '1180px',
		'--igp-container-full'        => $co['full'] ?? '100%',
		'--igp-container'             => 'min(' . ( $co['wide'] ?? '1180px' ) . ', calc(100vw - 40px))',
		'--igp-surface-default'       => $su['default'] ?? '#ffffff',
		'--igp-surface-elevated'      => $su['elevated'] ?? '#ffffff',
		'--igp-surface-soft'          => $su['soft'] ?? '#f6f8fb',
		'--igp-surface-brand'         => $su['brand'] ?? '#fff6ef',
	);

	foreach ( $map as $name => $value ) {
		$css[] = '  ' . $name . ': ' . $value . ';';
	}
	$css[] = '}';

	$css[] = '.igp-block, .igp-pro-hero, .igp-page-title { font-family: var(--igp-font-family); }';
	$css[] = '.igp-pro-hero__heading, .igp-page-title, .igp-block-heading { font-weight: var(--igp-heading-weight); letter-spacing: var(--igp-heading-letter-spacing); }';
	$css[] = '.igp-pro-hero__heading { font-size: var(--igp-hero-size); }';
	$css[] = '.igp-block-heading { font-size: var(--igp-section-heading-size); }';
	$css[] = '.igp-pro-hero__cta, .igp-pro-cta__button, .igp-button { border-radius: var(--igp-button-radius); font-weight: var(--igp-button-font-weight); padding: var(--igp-button-padding-y) var(--igp-button-padding-x); }';
	$css[] = '.igp-surface--default { background-color: var(--igp-surface-default); }';
	$css[] = '.igp-surface--soft { background-color: var(--igp-surface-soft); }';
	$css[] = '.igp-surface--brand { background-color: var(--igp-surface-brand); }';
	$css[] = '.igp-surface--elevated { background-color: var(--igp-surface-elevated); box-shadow: var(--igp-shadow-soft); }';
	$css[] = '.igp-container--narrow > * { max-width: var(--igp-container-narrow); }';
	$css[] = '.igp-container--default > * { max-width: var(--igp-container-default); }';
	$css[] = '.igp-container--wide > * { max-width: var(--igp-container-wide); }';

	return implode( "\n", $css ) . "\n";
}

/**
 * Invalidate generated brand CSS cache.
 */
function igp_pro_invalidate_brand_css_cache(): void {
	delete_option( IGP_PRO_BRAND_CSS_CACHE_OPTION );
}

/**
 * Generate active brand CSS if needed.
 *
 * @return array<string,string>|WP_Error
 */
function igp_pro_ensure_brand_css() {
	$tokens = igp_pro_resolve_design_tokens();
	$hash   = igp_pro_hash_design_tokens( $tokens );
	$cache  = get_option( IGP_PRO_BRAND_CSS_CACHE_OPTION, array() );

	if ( is_array( $cache ) && isset( $cache['hash'], $cache['relative_path'] ) && $cache['hash'] === $hash && file_exists( igp_pro_path( $cache['relative_path'] ) ) ) {
		return $cache;
	}

	if ( ! igp_pro_ensure_generated_css_storage() ) {
		return new WP_Error( 'igp_pro_css_storage_unavailable', __( 'Generated CSS storage is unavailable.', 'igp-pro' ) );
	}

	$active_id = function_exists( 'igp_pro_get_active_brand_profile_id' ) ? igp_pro_get_active_brand_profile_id() : 'default';
	$active_id = '' !== $active_id ? $active_id : 'default';
	$relative  = 'storage/generated-css/igp-brand-' . sanitize_file_name( $active_id ) . '-' . $hash . '.css';
	$path      = igp_pro_path( $relative );
	$css       = igp_pro_build_brand_css( $tokens );

	$result = file_put_contents( $path, $css ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
	if ( false === $result ) {
		return new WP_Error( 'igp_pro_css_write_failed', __( 'Generated CSS could not be written.', 'igp-pro' ) );
	}

	$cache = array(
		'hash'          => $hash,
		'profile_id'    => $active_id,
		'relative_path' => $relative,
		'generated_at'  => gmdate( 'c' ),
	);
	update_option( IGP_PRO_BRAND_CSS_CACHE_OPTION, $cache, false );

	if ( function_exists( 'igp_pro_log' ) ) {
		igp_pro_log(
			array(
				'actor_type'    => is_admin() ? 'human' : 'system',
				'operation'     => 'brand_css_generated',
				'object_type'   => 'brand_profile',
				'object_id'     => 0,
				'source_module' => 'brand_engine',
				'status'        => 'success',
				'summary'       => 'Generated brand CSS cache.',
			)
		);
	}

	return $cache;
}

/**
 * Return generated CSS URL if brand engine is enabled and CSS exists.
 *
 * @return string
 */
function igp_pro_get_generated_brand_css_url(): string {
	if ( function_exists( 'igp_feature_enabled' ) && ! igp_feature_enabled( 'enable_brand_engine' ) ) {
		return '';
	}

	$cache = igp_pro_ensure_brand_css();
	if ( is_wp_error( $cache ) || empty( $cache['relative_path'] ) ) {
		return '';
	}

	return igp_pro_url( $cache['relative_path'] );
}
